/*
 * Copyright 2010-2014 JetBrains s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jetbrains.jet.plugin.codeInsight;

import junit.framework.Assert;
import junit.framework.Test;
import junit.framework.TestSuite;

import java.io.File;
import java.util.regex.Pattern;
import org.jetbrains.jet.JetTestUtils;
import org.jetbrains.jet.test.InnerTestClasses;
import org.jetbrains.jet.test.TestMetadata;

import org.jetbrains.jet.plugin.codeInsight.AbstractJetInspectionTest;

/** This class is generated by {@link org.jetbrains.jet.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@InnerTestClasses({JetInspectionTestGenerated.Inspections.class, JetInspectionTestGenerated.Intentions.class})
public class JetInspectionTestGenerated extends AbstractJetInspectionTest {
    @TestMetadata("idea/testData/codeInsight/inspections")
    public static class Inspections extends AbstractJetInspectionTest {
        public void testAllFilesPresentInInspections() throws Exception {
            JetTestUtils.assertAllTestsPresentInSingleGeneratedClass(this.getClass(), "org.jetbrains.jet.generators.tests.TestsPackage", new File("idea/testData/codeInsight/inspections"), Pattern.compile("^(inspections\\.test)$"));
        }
        
        @TestMetadata("unnecessaryLabel/inspectionData/inspections.test")
        public void testUnnecessaryLabel_inspectionData_Inspections_test() throws Exception {
            doTest("idea/testData/codeInsight/inspections/unnecessaryLabel/inspectionData/inspections.test");
        }
        
    }
    
    @TestMetadata("idea/testData/intentions")
    public static class Intentions extends AbstractJetInspectionTest {
        public void testAllFilesPresentInIntentions() throws Exception {
            JetTestUtils.assertAllTestsPresentInSingleGeneratedClass(this.getClass(), "org.jetbrains.jet.generators.tests.TestsPackage", new File("idea/testData/intentions"), Pattern.compile("^(inspections\\.test)$"));
        }
        
        @TestMetadata("attributeCallReplacements/replaceGetIntention/inspectionData/inspections.test")
        public void testAttributeCallReplacements_replaceGetIntention_inspectionData_Inspections_test() throws Exception {
            doTest("idea/testData/intentions/attributeCallReplacements/replaceGetIntention/inspectionData/inspections.test");
        }
        
        @TestMetadata("branched/ifThenToElvis/inspectionData/inspections.test")
        public void testBranched_ifThenToElvis_inspectionData_Inspections_test() throws Exception {
            doTest("idea/testData/intentions/branched/ifThenToElvis/inspectionData/inspections.test");
        }
        
        @TestMetadata("branched/ifThenToSafeAccess/inspectionData/inspections.test")
        public void testBranched_ifThenToSafeAccess_inspectionData_Inspections_test() throws Exception {
            doTest("idea/testData/intentions/branched/ifThenToSafeAccess/inspectionData/inspections.test");
        }
        
    }
    
    public static Test suite() {
        TestSuite suite = new TestSuite("JetInspectionTestGenerated");
        suite.addTestSuite(Inspections.class);
        suite.addTestSuite(Intentions.class);
        return suite;
    }
}
